### ISSUE TITLE
404 not found error.

### ISSUE THREAD

**Issue by shenol** [agriya/rentnride#1]
{"message":"404 Not Found","status_code":404,"debug":{"line":460,"file":"C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(397): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#1 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(643): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#2 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(399): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#3 C:\\wamp64\\www\\rentgate\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 C:\\wamp64\\www\\rentgate\\vendor\\dingo\\api\\src\\Routing\\Router.php(513): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#5 C:\\wamp64\\www\\rentgate\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 C:\\wamp64\\www\\rentgate\\vendor\\illuminate\\pipeline\\Pipeline.php(150): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#8 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 C:\\wamp64\\www\\rentgate\\vendor\\illuminate\\pipeline\\Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#10 C:\\wamp64\\www\\rentgate\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#11 C:\\wamp64\\www\\rentgate\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#12 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 C:\\wamp64\\www\\rentgate\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#14 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#15 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#16 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#17 C:\\wamp64\\www\\rentgate\\vendor\\illuminate\\pipeline\\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#18 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(640): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#19 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(399): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#20 C:\\wamp64\\www\\rentgate\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(340): Laravel\\Lumen\\Application->dispatch(Object(Illuminate\\Http\\Request))","#21 C:\\wamp64\\www\\rentgate\\public\\index.php(41): Laravel\\Lumen\\Application->run(Object(Illuminate\\Http\\Request))","#22 {main}"]}}

**Comment by rrjanbiah** [comment]
@shenol Have you used `composer` to setup your dependencies? If so, can you also post your request API endpoint?

**Comment by shenol** [comment]
htaccess on RewriteBase "/bookorrent/public" erased the line worked.

**Comment by rrjanbiah** [comment]
@shenol So, is this fixed?

**Comment by rrjanbiah** [comment]
Closing this for now. If you get further issues, please feel free to reopen it
