### ISSUE TITLE
front end only display architecture

### ISSUE THREAD

**Issue by AFNANAMIN** [agriya/rentnride#2]
![image](https://user-images.githubusercontent.com/33934146/64587703-a3153f80-d3b9-11e9-9fb6-3801294a343e.png)
i just show this in all files instead of actual front end

**Comment by rrjanbiah** [comment]
@AFNANAMIN Most likely it is a setup issue. So, please double check your configurations

**Comment by AFNANAMIN** [comment]
can you guide me about it because i already did what i know about project cloning of laravel

**Comment by rrjanbiah** [comment]
@AFNANAMIN We're extremely sorry that we don't have bandwidth to provide free support. You may however make use of our paid support https://www.agriya.com/products/car-rental-script
